/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  PoWPayerTimeLock,
  PoWPayerTimeLockInterface,
} from "../PoWPayerTimeLock";

const _abi = [
  {
    inputs: [],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "getBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "receiver",
        type: "address",
      },
    ],
    name: "pay",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x6080604052600060018190555043600281905550610330806100226000396000f3fe60806040526004361061002d5760003560e01c80630c11dedd1461003657806312065fe01461005257610034565b3661003457005b005b610050600480360381019061004b919061019b565b61007d565b005b34801561005e57600080fd5b5061006761017e565b60405161007491906101d3565b60405180910390f35b67016345785d8a000060015410156101615767016345785d8a0000652d79883d20006001546100ac91906101ee565b11610103578073ffffffffffffffffffffffffffffffffffffffff166108fc652d79883d20009081150290604051600060405180830381858888f193505050501580156100fd573d6000803e3d6000fd5b50610160565b8073ffffffffffffffffffffffffffffffffffffffff166108fc60015467016345785d8a00006101339190610244565b9081150290604051600060405180830381858888f1935050505015801561015e573d6000803e3d6000fd5b505b5b60025443111561017b576000600181905550436002819055505b50565b600047905090565b600081359050610195816102e3565b92915050565b6000602082840312156101ad57600080fd5b60006101bb84828501610186565b91505092915050565b6101cd816102aa565b82525050565b60006020820190506101e860008301846101c4565b92915050565b60006101f9826102aa565b9150610204836102aa565b9250827fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff03821115610239576102386102b4565b5b828201905092915050565b600061024f826102aa565b915061025a836102aa565b92508282101561026d5761026c6102b4565b5b828203905092915050565b60006102838261028a565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b6102ec81610278565b81146102f757600080fd5b5056fea2646970667358221220689c501f8d03744398ee78696e44d8f730c2fdcb461e9c83bfaac8f041882cea64736f6c63430008040033";

export class PoWPayerTimeLock__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<PoWPayerTimeLock> {
    return super.deploy(overrides || {}) as Promise<PoWPayerTimeLock>;
  }
  getDeployTransaction(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PoWPayerTimeLock {
    return super.attach(address) as PoWPayerTimeLock;
  }
  connect(signer: Signer): PoWPayerTimeLock__factory {
    return super.connect(signer) as PoWPayerTimeLock__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoWPayerTimeLockInterface {
    return new utils.Interface(_abi) as PoWPayerTimeLockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoWPayerTimeLock {
    return new Contract(address, _abi, signerOrProvider) as PoWPayerTimeLock;
  }
}
