/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PoWPayer, PoWPayerInterface } from "../PoWPayer";

const _abi = [
  {
    inputs: [],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "getBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "receiver",
        type: "address",
      },
    ],
    name: "pay",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x60806040526101c7806100136000396000f3fe60806040526004361061002d5760003560e01c80630c11dedd1461003657806312065fe01461005257610034565b3661003457005b005b610050600480360381019061004b91906100eb565b61007d565b005b34801561005e57600080fd5b506100676100ce565b6040516100749190610123565b60405180910390f35b8073ffffffffffffffffffffffffffffffffffffffff166108fc6611c37937e080009081150290604051600060405180830381858888f193505050501580156100ca573d6000803e3d6000fd5b5050565b600047905090565b6000813590506100e58161017a565b92915050565b6000602082840312156100fd57600080fd5b600061010b848285016100d6565b91505092915050565b61011d81610170565b82525050565b60006020820190506101386000830184610114565b92915050565b600061014982610150565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b6101838161013e565b811461018e57600080fd5b5056fea264697066735822122077ba3886941e0e9c6332185328acb347ada3d6d524a367964340229dd694571c64736f6c63430008040033";

export class PoWPayer__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<PoWPayer> {
    return super.deploy(overrides || {}) as Promise<PoWPayer>;
  }
  getDeployTransaction(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PoWPayer {
    return super.attach(address) as PoWPayer;
  }
  connect(signer: Signer): PoWPayer__factory {
    return super.connect(signer) as PoWPayer__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoWPayerInterface {
    return new utils.Interface(_abi) as PoWPayerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoWPayer {
    return new Contract(address, _abi, signerOrProvider) as PoWPayer;
  }
}
