/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "PoWDeveloper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoWDeveloper__factory>;
    getContractFactory(
      name: "PoWPayer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoWPayer__factory>;
    getContractFactory(
      name: "PoWPayerTimeLock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoWPayerTimeLock__factory>;
    getContractFactory(
      name: "PoWSecure",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoWSecure__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "PoWDeveloper",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PoWDeveloper>;
    getContractAt(
      name: "PoWPayer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PoWPayer>;
    getContractAt(
      name: "PoWPayerTimeLock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PoWPayerTimeLock>;
    getContractAt(
      name: "PoWSecure",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PoWSecure>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
